"use client";

import { useState } from "react";
import { useFeedStore } from "@/store/feed";
import { Target, CheckCircle2, XCircle, ArrowRight } from "lucide-react";

export function CheckpointCard({ card }: { card: any }) {
  const { recordEvent, setAssessmentActive } = useFeedStore();
  const [started, setStarted] = useState(false);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);

  // Mock questions for the checkpoint (In Phase 4, these will be generated by LLM based on objectives)
  const questions = card.questions || [
    { q: "What is the primary purpose of a closure?", options: ["Data privacy", "Faster loops", "DOM manipulation"], correct: 0 },
    { q: "Which phase creates the Execution Context?", options: ["Execution Phase", "Creation Phase", "Garbage Collection"], correct: 1 },
    { q: "Does hoisting apply to let and const?", options: ["Yes, initialized to undefined", "Yes, but in Temporal Dead Zone", "No, they are not hoisted"], correct: 1 },
  ];

  const handleAnswer = (selectedIndex: number) => {
    if (selectedIndex === questions[currentQuestion].correct) {
      setScore(s => s + 1);
    }
    
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(c => c + 1);
    } else {
      setFinished(true);
      setAssessmentActive(false);
      recordEvent(card.id, { completed: true });
    }
  };

  const passed = score >= 2;

  return (
    <div className="w-full min-h-[100dvh] flex items-center justify-center px-4 pb-6 pt-16 snap-center relative">
      <div className="w-full max-w-md mx-auto h-full max-h-[850px]">
        <div className="glass-card h-full p-8 border-accent-amber/30 relative overflow-y-auto scrollbar-none flex flex-col justify-center">
          
          {/* Background glow */}
          <div className="absolute top-0 right-0 w-32 h-32 bg-accent-amber/10 blur-[50px] pointer-events-none" />

          {!started && !finished && (
            <div className="text-center animate-fade-in-up">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-accent-amber/10 text-accent-amber mb-6">
                <Target className="w-8 h-8" />
              </div>
              <h2 className="text-2xl font-bold text-foreground mb-2">Checkpoint</h2>
              <p className="text-foreground/60 mb-8">Let's verify what you've learned so far.</p>
              
              <div className="flex justify-center gap-6 mb-8 text-sm font-bold text-foreground/80">
                <div className="flex flex-col items-center">
                  <span className="text-2xl text-accent-amber mb-1">{questions.length}</span>
                  <span className="text-[10px] uppercase tracking-widest text-foreground/40">Questions</span>
                </div>
                <div className="flex flex-col items-center">
                  <span className="text-2xl text-accent-amber mb-1">1</span>
                  <span className="text-[10px] uppercase tracking-widest text-foreground/40">Minute</span>
                </div>
              </div>

              <button 
                onClick={() => {
                  setStarted(true);
                  setAssessmentActive(true);
                }}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-accent-amber to-orange-500 text-white font-bold transition-all hover:scale-[1.02] active:scale-[0.98] shadow-lg shadow-accent-amber/20"
              >
                Start Assessment
              </button>
            </div>
          )}

          {started && !finished && (
            <div className="animate-fade-in-up">
              <div className="flex justify-between items-center mb-6">
                <span className="text-xs font-bold uppercase tracking-widest text-accent-amber">Question {currentQuestion + 1} of {questions.length}</span>
                <button 
                  onClick={() => {
                    setStarted(false);
                    setAssessmentActive(false);
                    setCurrentQuestion(0);
                    setScore(0);
                  }}
                  className="text-xs font-bold uppercase tracking-widest text-foreground/40 hover:text-accent-rose transition-colors"
                >
                  Cancel
                </button>
              </div>
              
              <h3 className="text-xl font-bold text-foreground mb-8 leading-tight">{questions[currentQuestion].q}</h3>
              
              <div className="space-y-3">
                {questions[currentQuestion].options.map((opt: string, idx: number) => (
                  <button
                    key={idx}
                    onClick={() => handleAnswer(idx)}
                    className="w-full text-left p-4 rounded-xl border border-[rgba(139,148,255,0.1)] hover:border-[rgba(139,148,255,0.3)] bg-surface/50 transition-all hover:bg-white/5"
                  >
                    <span className="font-medium text-sm">{opt}</span>
                  </button>
                ))}
              </div>
            </div>
          )}

          {finished && (
            <div className="text-center animate-fade-in-up">
              <div className={`inline-flex items-center justify-center w-20 h-20 rounded-full mb-6 ${passed ? 'bg-accent-emerald/10 text-accent-emerald' : 'bg-accent-rose/10 text-accent-rose'}`}>
                {passed ? <CheckCircle2 className="w-10 h-10" /> : <XCircle className="w-10 h-10" />}
              </div>
              <h2 className="text-3xl font-bold text-foreground mb-2">
                {score} / {questions.length}
              </h2>
              <p className={`text-lg font-bold mb-8 ${passed ? 'text-accent-emerald' : 'text-accent-rose'}`}>
                {passed ? 'Passed!' : 'Needs Revision'}
              </p>

              {!passed && (
                <div className="p-4 rounded-xl bg-accent-rose/5 border border-accent-rose/20 text-left mb-8">
                  <p className="text-xs text-foreground/60 mb-2 uppercase tracking-widest font-bold">Recommended Review</p>
                  <ul className="text-sm text-foreground/80 space-y-2">
                    <li className="flex items-center gap-2"><ArrowRight className="w-3 h-3 text-accent-rose" /> Execution Context</li>
                    <li className="flex items-center gap-2"><ArrowRight className="w-3 h-3 text-accent-rose" /> Hoisting</li>
                  </ul>
                </div>
              )}

              <button 
                onClick={() => {
                  const container = document.getElementById("feed-scroll-container");
                  if (container) {
                    container.scrollBy({ top: window.innerHeight, behavior: "smooth" });
                  }
                }}
                className="w-full py-4 rounded-xl bg-surface border border-white/10 text-foreground font-bold transition-all hover:bg-white/5"
              >
                Continue Scrolling
              </button>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}
