"use client";
import { useState, useEffect } from "react";
import { CheckCircle2, XCircle, ArrowRight, Star, Bug, GitCompare, MessageSquare, AlertCircle, Target } from "lucide-react";
import { useFeedStore } from "@/store/feed";
import { useSound } from "@/hooks/useSound";
import { QuestionPrimitive, ExplanationPrimitive, FeedbackPrimitive, ConfidencePrimitive, SelectionPrimitive } from "./primitives";
import CardWrapper from "./CardWrapper";

// ---------------------------------------------------------
// Explain In Your Own Words Card
// ---------------------------------------------------------
export function ExplainCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [answer, setAnswer] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [rating, setRating] = useState<'guess' | 'somewhat' | 'sure' | null>(null);

  const handleSubmit = () => {
    if (answer.trim().length > 5) {
      setSubmitted(true);
    }
  };

  const handleRate = (score: 'guess' | 'somewhat' | 'sure') => {
    setRating(score);
    recordEvent(card.id, { completed: true, confidence: score });
  };

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <QuestionPrimitive text={card.payload.prompt} subtitle="Explain In Your Own Words" />
        
        {!submitted ? (
          <div className="flex-1 flex flex-col gap-4 animate-fade-in-up mt-6">
            <textarea 
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
              placeholder="Type your explanation here..."
              className="w-full flex-1 min-h-[150px] p-4 rounded-xl bg-surface border border-[rgba(139,148,255,0.1)] focus:border-accent-primary/50 outline-none resize-none text-sm text-foreground/80 leading-relaxed transition-colors placeholder:text-foreground/30"
            />
            <button 
              onClick={() => { playClick(); handleSubmit(); }}
              disabled={answer.trim().length < 5}
              className="w-full py-3.5 rounded-xl bg-accent-primary text-white font-bold disabled:opacity-30 transition-all hover:bg-accent-primary/90 active:scale-[0.98]"
            >
              Reveal Model Answer
            </button>
          </div>
        ) : (
          <div className="animate-fade-in-up mt-6">
            <div className="p-4 rounded-xl bg-surface border border-white/5 mb-6">
              <div className="text-[10px] font-bold uppercase tracking-widest text-accent-emerald mb-3">Model Answer</div>
              <p className="text-sm text-foreground/80 leading-relaxed whitespace-pre-wrap">{card.payload.modelAnswer}</p>
            </div>
            
            {!rating && (
              <div className="mt-8">
                <ConfidencePrimitive onRate={handleRate} />
              </div>
            )}
          </div>
        )}
      </div>
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Debug Card
// ---------------------------------------------------------
export function DebugCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [selectedLine, setSelectedLine] = useState<number | null>(null);
  const [submitted, setSubmitted] = useState(false);
  
  const codeString = Array.isArray(card.payload.code) ? card.payload.code.join('\n') : String(card.payload.code || '');
  // Split on actual newlines OR literal \n characters generated by LLMs
  const lines = codeString.split(/\\n|\n/);
  const targetIdx = card.payload.bugLineIndex !== undefined ? card.payload.bugLineIndex : (card.payload.bugLine !== undefined ? card.payload.bugLine - 1 : -1);
  const isCorrect = selectedLine === targetIdx;

  const handleSubmit = () => {
    if (selectedLine !== null) {
      setSubmitted(true);
      recordEvent(card.id, { completed: isCorrect });
    }
  };

  return (
    <CardWrapper card={card}>
      <div className="px-4 py-1.5 bg-accent-rose/20 text-accent-rose text-[10px] font-bold uppercase tracking-widest rounded-full mb-6 self-start flex items-center gap-2 w-fit">
        <Bug className="w-3 h-3" /> Find The Bug
      </div>
      
      <h3 className="text-xl font-bold text-foreground mb-6 leading-tight">{card.payload.question}</h3>
      
      <div className="bg-[#0d0d12] border border-white/10 rounded-xl overflow-hidden mb-6">
        {lines.map((line: string, idx: number) => {
          const isSelected = selectedLine === idx;
          const isBug = submitted && isCorrect && targetIdx === idx;
          const isWrongSelection = submitted && isSelected && !isBug;
          
          let bgClass = "bg-transparent";
          if (!submitted && isSelected) bgClass = "bg-accent-primary/20";
          if (submitted && isBug) bgClass = "bg-accent-emerald/20 border-y border-accent-emerald/30";
          if (isWrongSelection) bgClass = "bg-accent-rose/20 border-y border-accent-rose/30";

          return (
            <div 
              key={idx} 
              onClick={() => !submitted && setSelectedLine(idx)}
              className={`flex items-start text-sm font-mono cursor-pointer transition-colors hover:bg-white/5 py-1 ${bgClass}`}
            >
              <div className="w-8 flex-shrink-0 text-right pr-3 text-foreground/30 select-none">{idx + 1}</div>
              <div className={`whitespace-pre overflow-x-auto ${isBug ? 'text-emerald-300' : isWrongSelection ? 'text-rose-300' : 'text-accent-secondary'}`}>{line || ' '}</div>
            </div>
          );
        })}
      </div>

      {!submitted ? (
        <button 
          onClick={() => { playClick(); handleSubmit(); }}
          disabled={selectedLine === null}
          className="w-full mt-6 py-3.5 rounded-xl bg-accent-primary text-white font-bold disabled:opacity-30 transition-all hover:bg-accent-primary/90"
        >
          Verify Bug
        </button>
      ) : (
        <div className="mt-6">
          <FeedbackPrimitive isCorrect={isCorrect} message={isCorrect ? "Excellent eye!" : "Not quite."} />
          <ExplanationPrimitive text={card.payload.explanation} />
          {!isCorrect && (
            <button onClick={() => { playClick(); setSubmitted(false);  setSelectedLine(null); }} className="mt-4 px-4 py-2 rounded-lg bg-surface border border-accent-primary/30 text-xs font-bold text-accent-primary hover:bg-accent-primary/10 transition-all">
              Try again
            </button>
          )}
        </div>
      )}
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Scenario Card
// ---------------------------------------------------------
export function ScenarioCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    if (selectedId && !submitted) {
      setSubmitted(true);
      const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;
      recordEvent(card.id, { completed: !!isCorrect });
    }
  };

  const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <QuestionPrimitive text={card.payload.question} subtitle="Architecture Scenario" />
        
        <div className="p-4 rounded-xl bg-surface border border-white/5 mb-6 text-sm text-foreground/80 leading-relaxed border-l-2 border-l-accent-secondary animate-fade-in-up">
          {card.payload.scenario}
        </div>

        {!submitted ? (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={setSelectedId}
          />
        ) : (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={() => {}}
            disabled={true}
          />
        )}

        {!submitted ? (
          <button onClick={() => { playClick(); handleSubmit(); }} disabled={!selectedId} className="w-full mt-6 py-3.5 rounded-xl bg-accent-primary text-white font-bold disabled:opacity-30 hover:bg-accent-primary/90 transition-all">
            Make Decision
          </button>
        ) : (
          <div className="mt-6 animate-fade-in-up">
            <FeedbackPrimitive isCorrect={!!isCorrect} message={isCorrect ? "Correct Decision!" : "Suboptimal Decision"} />
            <ExplanationPrimitive text={card.payload.options.find((o:any)=>o.id===selectedId)?.explanation} />
            {!isCorrect && (
              <button onClick={() => { playClick(); setSubmitted(false);  setSelectedId(null); }} className="mt-4 px-4 py-2 rounded-lg bg-surface border border-accent-primary/30 text-xs font-bold text-accent-primary hover:bg-accent-primary/10 transition-all">
                Re-evaluate
              </button>
            )}
          </div>
        )}
      </div>
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Incident Card
// ---------------------------------------------------------

export function IncidentCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    if (selectedId && !submitted) {
      setSubmitted(true);
      const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;
      recordEvent(card.id, { completed: !!isCorrect });
    }
  };

  const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-red-500/20 text-red-500 flex items-center justify-center">
            <AlertCircle className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs font-black tracking-widest text-red-500/70 uppercase">Production Incident</div>
            <h2 className="text-xl font-bold leading-tight">{card.payload.question}</h2>
          </div>
        </div>
        
        <div className="p-4 rounded-xl bg-surface border border-red-500/20 mb-6 text-sm text-foreground/80 leading-relaxed border-l-2 border-l-red-500 font-mono animate-fade-in-up whitespace-pre-line">
          {card.payload.incident}
        </div>

        {!submitted ? (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={setSelectedId}
          />
        ) : (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={() => {}}
            disabled={true}
          />
        )}

        {!submitted ? (
          <button onClick={() => { playClick(); handleSubmit(); }} disabled={!selectedId} className="w-full mt-6 py-3.5 rounded-xl bg-red-600 text-white font-bold disabled:opacity-30 hover:bg-red-700 transition-all shadow-lg shadow-red-900/20">
            Investigate
          </button>
        ) : (
          <div className="mt-6 animate-fade-in-up">
            <FeedbackPrimitive isCorrect={!!isCorrect} message={isCorrect ? "Correct Diagnosis!" : "Incorrect Diagnosis"} />
            <ExplanationPrimitive text={card.payload.options.find((o:any)=>o.id===selectedId)?.explanation} />
            {!isCorrect && (
              <button onClick={() => { playClick(); setSubmitted(false);  setSelectedId(null); }} className="mt-4 px-4 py-2 rounded-lg bg-surface border border-red-500/30 text-xs font-bold text-red-400 hover:bg-red-500/10 transition-all">
                Try Another Lead
              </button>
            )}
          </div>
        )}
      </div>
    </CardWrapper>
  );
}

// (Legacy CompareCard removed, moved to PracticeCards)

// ---------------------------------------------------------
// Tradeoff Duel Card
// ---------------------------------------------------------
export function TradeoffCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    if (selectedId && !submitted) {
      setSubmitted(true);
      const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;
      recordEvent(card.id, { completed: !!isCorrect });
    }
  };

  const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-accent-amber/20 text-accent-amber flex items-center justify-center">
            <GitCompare className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs font-black tracking-widest text-accent-amber/70 uppercase">Tradeoff Duel</div>
            <h2 className="text-xl font-bold leading-tight">{card.payload.question}</h2>
          </div>
        </div>
        
        <div className="flex items-center justify-center gap-4 my-6">
          <div className="px-4 py-3 rounded-lg bg-surface border border-white/10 font-bold text-center flex-1">{card.payload.optionA}</div>
          <div className="text-xs font-black text-foreground/30 italic">VS</div>
          <div className="px-4 py-3 rounded-lg bg-surface border border-white/10 font-bold text-center flex-1">{card.payload.optionB}</div>
        </div>

        <div className="p-4 rounded-xl bg-surface border border-white/5 mb-6 text-sm text-foreground/80 leading-relaxed border-l-2 border-l-accent-amber animate-fade-in-up whitespace-pre-line">
          {card.payload.scenario}
        </div>

        {!submitted ? (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={setSelectedId}
          />
        ) : (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={() => {}}
            disabled={true}
          />
        )}

        {!submitted ? (
          <button onClick={() => { playClick(); handleSubmit(); }} disabled={!selectedId} className="w-full mt-6 py-3.5 rounded-xl bg-accent-amber text-black font-bold disabled:opacity-30 hover:bg-accent-amber/90 transition-all shadow-lg shadow-accent-amber/20">
            Lock In Choice
          </button>
        ) : (
          <div className="mt-6 animate-fade-in-up">
            <FeedbackPrimitive isCorrect={!!isCorrect} message={isCorrect ? "Solid Architecture!" : "Flawed Architecture"} />
            <ExplanationPrimitive text={card.payload.options.find((o:any)=>o.id===selectedId)?.explanation} />
            {!isCorrect && (
              <button onClick={() => { playClick(); setSubmitted(false);  setSelectedId(null); }} className="mt-4 px-4 py-2 rounded-lg bg-surface border border-accent-amber/30 text-xs font-bold text-accent-amber hover:bg-accent-amber/10 transition-all">
                Rethink Tradeoffs
              </button>
            )}
          </div>
        )}
      </div>
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Estimation Challenge Card
// ---------------------------------------------------------
import { Calculator } from "lucide-react";

export function EstimationCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    if (selectedId && !submitted) {
      setSubmitted(true);
      const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;
      recordEvent(card.id, { completed: !!isCorrect });
    }
  };

  const isCorrect = card.payload.options.find((o: any) => o.id === selectedId)?.isCorrect;

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-accent-secondary/20 text-accent-secondary flex items-center justify-center">
            <Calculator className="w-5 h-5" />
          </div>
          <div>
            <div className="text-xs font-black tracking-widest text-accent-secondary/70 uppercase">Back-of-the-envelope</div>
            <h2 className="text-xl font-bold leading-tight">{card.payload.question}</h2>
          </div>
        </div>
        
        <div className="p-4 rounded-xl bg-surface border border-accent-secondary/20 mb-6 text-sm text-foreground/80 leading-relaxed font-mono animate-fade-in-up whitespace-pre-line">
          {card.payload.scenario}
        </div>

        {!submitted ? (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={setSelectedId}
          />
        ) : (
          <SelectionPrimitive 
            options={card.payload.options.map((o: any) => ({ id: o.id, label: o.text }))}
            selectedIds={selectedId ? [selectedId] : []}
            onSelect={() => {}}
            disabled={true}
          />
        )}

        {!submitted ? (
          <button onClick={() => { playClick(); handleSubmit(); }} disabled={!selectedId} className="w-full mt-6 py-3.5 rounded-xl bg-accent-secondary text-white font-bold disabled:opacity-30 hover:bg-accent-secondary/90 transition-all shadow-lg shadow-accent-secondary/20">
            Calculate
          </button>
        ) : (
          <div className="mt-6 animate-fade-in-up">
            <FeedbackPrimitive isCorrect={!!isCorrect} message={isCorrect ? "Math Checks Out!" : "Math Is Off"} />
            <ExplanationPrimitive text={card.payload.options.find((o:any)=>o.id===selectedId)?.explanation} />
            {!isCorrect && (
              <button onClick={() => { playClick(); setSubmitted(false);  setSelectedId(null); }} className="mt-4 px-4 py-2 rounded-lg bg-surface border border-accent-secondary/30 text-xs font-bold text-accent-secondary hover:bg-accent-secondary/10 transition-all">
                Recalculate
              </button>
            )}
          </div>
        )}
      </div>
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Why It Matters Card
// ---------------------------------------------------------
export function WhyItMattersCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const { recordEvent } = useFeedStore();
  
  // Auto complete on view
  useEffect(() => {
    recordEvent(card.id, { completed: true });
  }, []);

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-accent-emerald to-accent-secondary mb-8 shadow-lg shadow-accent-emerald/20">
          <Target className="w-8 h-8 text-white" />
        </div>
        
        <h2 className="text-3xl font-bold text-foreground mb-4">Why {card.payload.topic} Matters</h2>
        <p className="text-lg text-foreground/60 leading-relaxed mb-8">
          {card.payload.explanation}
        </p>

        <div className="p-4 rounded-xl bg-surface border border-white/5 border-l-2 border-l-accent-amber">
          <div className="text-[10px] font-bold uppercase tracking-widest text-accent-amber mb-2">Interview Context</div>
          <p className="text-sm text-foreground/80">{card.payload.interviewContext}</p>
        </div>
      </div>
    </CardWrapper>
  );
}

// ---------------------------------------------------------
// Topic Complete Card
// ---------------------------------------------------------
import { Trophy } from "lucide-react";
import { useRouter } from "next/navigation";

export function TopicCompleteCard({ card }: { card: any }) {
  const { playClick } = useSound();
  const router = useRouter();

  return (
    <CardWrapper card={card}>
      <div className="flex flex-col h-full justify-center items-center text-center px-4">
        <div className="relative mb-12">
          <div className="absolute inset-0 bg-accent-amber/20 blur-3xl rounded-full"></div>
          <div className="w-24 h-24 rounded-full bg-gradient-to-br from-accent-amber to-accent-primary p-1 shadow-2xl shadow-accent-amber/30 relative z-10 animate-bounce">
            <div className="w-full h-full bg-surface rounded-full flex items-center justify-center">
              <Trophy className="w-12 h-12 text-accent-amber" />
            </div>
          </div>
        </div>
        
        <div className="inline-block px-4 py-1.5 rounded-full bg-accent-amber/10 border border-accent-amber/20 mb-6 animate-fade-in-up">
          <span className="text-xs font-bold uppercase tracking-widest text-accent-amber">Curriculum Mastered</span>
        </div>
        
        <h2 className="text-4xl font-black mb-4 animate-fade-in-up" style={{ animationDelay: "100ms" }}>
          Topic Completed!
        </h2>
        
        <p className="text-foreground/60 leading-relaxed mb-12 max-w-sm animate-fade-in-up" style={{ animationDelay: "200ms" }}>
          You have successfully completed all activities and scenarios for <strong className="text-foreground">{card.payload.topicTitle}</strong>.
        </p>

        <div className="w-full max-w-xs space-y-4 animate-fade-in-up" style={{ animationDelay: "300ms" }}>
          <button 
            onClick={() => router.push(`/topics/${card.topicId}`)}
            className="w-full py-4 rounded-xl bg-accent-primary text-white font-bold transition-all hover:bg-accent-primary/90 hover:-translate-y-1 shadow-[0_10px_30px_-10px_rgba(139,148,255,0.4)]"
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    </CardWrapper>
  );
}
